import Head from "next/head";
import React from "react";
import { useState, useEffect } from "react";
import styled from "styled-components";
import ThreeGrid from '../components/boxesGrid';
import BoxR from "@/components/BoxRotating";
import CubeScene from "@/components/CubeTestScenario";

const MainContainer = styled.div`
 
 /* background: rgb(73, 72, 77);
  background: radial-gradient(
    circle at 50% 10%,
    rgba(73, 72, 77, 1) 0%,
    rgba(0, 0, 0, 1) 100%
  );*/
  //display: grid;
  //grid-template-columns: repeat(1, 1fr);
  //grid-template-rows: repeat(1, 1fr);
  //left: 0;
  //top: 0;
 // position: absolute;
  //z-index: 1;
  background-color: #dddddd;
  width: 100vw;
  height: 100vh;
  margin: 0;
    padding: 0;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
       
        {/*<ThreeGrid />*/}
        <BoxR/>
        <CubeScene/>
          
       
      </MainContainer>
    </>
  );
}
